// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNgO8JDjFfVmWMbjZuQfIIW7IekJB-SyI',
    appId: '1:408889408386:web:fe474fd008873874ca6d9b',
    messagingSenderId: '408889408386',
    projectId: 'missyou-d9029',
    authDomain: 'missyou-d9029.firebaseapp.com',
    storageBucket: 'missyou-d9029.firebasestorage.app',
    measurementId: 'G-FHW88WZY0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvSwaODqPZMXLpfvd9y84wKUW-R80vk60',
    appId: '1:408889408386:android:edd79bb4ee7ddbfbca6d9b',
    messagingSenderId: '408889408386',
    projectId: 'missyou-d9029',
    storageBucket: 'missyou-d9029.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Rx8zEvUZyRwCmLQu6dmPU99M4nBHwcU',
    appId: '1:408889408386:ios:7f22689bce8cf065ca6d9b',
    messagingSenderId: '408889408386',
    projectId: 'missyou-d9029',
    storageBucket: 'missyou-d9029.firebasestorage.app',
    iosBundleId: 'com.example.missYou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6Rx8zEvUZyRwCmLQu6dmPU99M4nBHwcU',
    appId: '1:408889408386:ios:7f22689bce8cf065ca6d9b',
    messagingSenderId: '408889408386',
    projectId: 'missyou-d9029',
    storageBucket: 'missyou-d9029.firebasestorage.app',
    iosBundleId: 'com.example.missYou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNgO8JDjFfVmWMbjZuQfIIW7IekJB-SyI',
    appId: '1:408889408386:web:229262a5fa4bc393ca6d9b',
    messagingSenderId: '408889408386',
    projectId: 'missyou-d9029',
    authDomain: 'missyou-d9029.firebaseapp.com',
    storageBucket: 'missyou-d9029.firebasestorage.app',
    measurementId: 'G-KPYHXE0PYS',
  );
}
